from __future__ import annotations

from typing import Protocol, Sequence
from .types import JointState, Pose, RobotState


class RobotBackend(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def state(self) -> RobotState: ...
    def move_joints(self, joints: Sequence[float]) -> None: ...
    def move_p(self, pose: Pose) -> None: ...
    def gripper(self, width: float, effort: float | None = None) -> None: ...
    def stop(self) -> None: ...
